#!/bin/bash
HEIGHT=18
CHOICE_HEIGHT=25
WIDTH=78
BACKTITLE="SYSTEM MENU"
TITLE="[ M A I N - M E N U ]"
MENU="Keybindings:"

dialog --colors --no-ok --no-collapse --menu "Key bindings:" 18 78 18 "Launch a terminal" "Windows + Shift + Enter" "Lock screen" "Windows + F1" "Launch dmenu" "Windows + Shift + d" "Launch rofi menu" "Windows + o" "Launch center menu" "Windows + p" "Close menus or launchers" "Windows + Shift + p" "Launch sidebar" "Windows + s" "Close sidebar" "Windows + Shift + s" "Increase volume by 5" "Windows + Right button" "Decrease volume by 5" "Windows + Left" "Increase brightness by 5" "Windows + Up button" "Decrease brightness by 5" "Windows + Down button" "Take screenshot" "Windows + Print" "Copy to clipboard" "Print" "Bar toggle" "Windows + b" "Activate inhibitor" "Windows + z" "Close window" "Windows + Shift + c" "Close gaps of window" "Windows + Ctrl + g" "Toggle all gaps" "Windows + Shift + g" "Incremenet left-hand gap" "Windows + Ctrl + t" "Decremenet left-hand gap" "Windows + Shift + t" "Increment the top gap" "Windows + Ctrl + y" "Decrement the top gap" "Windows + Shift + y" "Increment the bottom gap" "Windows + Ctrl + u" "Decrement the bottom gap" "Windows + Shift + u" "Increment the right-hand side" "Windows + Shift + i" "Decrement the left-hand side" "Windows + Shift + i" "Rotate through the available layout algorithms" "Windows + space" "Reset the layouts on the current workspace to default" "Windows + Shift + space" "Resize viewed windows to the current size" "Windows + n" "Move focus to the next window" "Windows + Tab or Windows + j" "Move focus to the previous window" "Windows + k" "Move focus to the master window" "Windows + m" "Rofi menu for applications" "Windows + Shift + m" "Swap the focused window and the master" "Windows + Enter" "Swap the focused window with the next window" "Windows + Shift + j" "Swap the focused window with the previous window" "Windows + Shift + k" "Shrink the master area" "Windows + h" "Expand the master are" "Windows + l" "Push window back into tiling" "Windows + t" "Increment the number of windows in the master area" "Windows + comma" "Deincrement the number of windows in the master area" "Windows + period" "Toggle the status bar gap" "Windows + b" "Quit xmonad" "Windows + Shift + q" "Restart xmonad" "Windows + q" "Rofi Pentester/Hacking tool" "Windows + Shift + h" "Windows + [1..9]" "Switch to workspace n"
